server:
  port: 8080
  # to prevent error:
  # The bean 'oauth2ClientContext', defined in class path resource [.../OAuth2RestOperationsConfiguration$SingletonScopedConfiguration.class],
  # could not be registered. A bean with that name has already been defined in BeanDefinition defined in class path resource
  # [.../OAuth2ClientConfiguration$OAuth2ClientContextConfiguration.class] and overriding is disabled.

spring:

  main:
    allow-bean-definition-overriding: true

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/nplusone
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
          #time_zone: ${time-zone}

  #flyway:
  #  locations: classpath:db/migration
  #  baselineOnMigrate: true